version: "3"

services:

  pypi_package_bot:
    container_name: pypi_package_bot
    build: .
    command: "python /app/main.py"
    volumes:
      - ./bot_persistence.db:/app/bot_persistence.db
    env_file:
      - ".env"
